//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acme.Packages.Menu {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources1() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Acme.Packages.Menu.Resources", typeof(Resources1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exportar estructura de tablas.
        /// </summary>
        internal static string CmdExportTableStructure_Name {
            get {
                return ResourceManager.GetString("CmdExportTableStructure_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exportar Source Code.
        /// </summary>
        internal static string CmdExportProcedureSource_Name {
            get {
                return ResourceManager.GetString("CmdExportProcedureSource_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generar Log.
        /// </summary>
        internal static string CmdGenerateLogDebug_Name {
            get {
                return ResourceManager.GetString("CmdGenerateLogDebug_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &amp;Crear Transaccion.
        /// </summary>
        internal static string CreateTransaction {
            get {
                return ResourceManager.GetString("CreateTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a My Commands.
        /// </summary>
        internal static string MyCommands {
            get {
                return ResourceManager.GetString("MyCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a My &amp;First Command.
        /// </summary>
        internal static string MyFirstCommand {
            get {
                return ResourceManager.GetString("MyFirstCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a My &amp;Second Command.
        /// </summary>
        internal static string MySecondCommand {
            get {
                return ResourceManager.GetString("MySecondCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exportar History.
        /// </summary>
        internal static string ShowObjectHistory_Name {
            get {
                return ResourceManager.GetString("ShowObjectHistory_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Extraer Log.
        /// </summary>
        internal static string WGExtractProcedure_Name {
            get {
                return ResourceManager.GetString("WGExtractProcedure_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar Variable.
        /// </summary>
        internal static string WGExtractVariable_Name {
            get {
                return ResourceManager.GetString("WGExtractVariable_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &amp;Why not Another Command?.
        /// </summary>
        internal static string WhyNotAnotherCommand {
            get {
                return ResourceManager.GetString("WhyNotAnotherCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &amp;Yet Another Command.
        /// </summary>
        internal static string YetAnotherCommand {
            get {
                return ResourceManager.GetString("YetAnotherCommand", resourceCulture);
            }
        }
    }
}
